[package]
name = "websites-test"
version = "0.1.0"
authors = ["rpurser"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
selenium-rs = "0.1.0"