name: Make and Push Docker Image to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master
          
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: 'Build docker image and push to Azure'
        uses: azure/docker-login@v1
        with:
          login-server: snakegameregistry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: actions/checkout@v2
      - name: Build the Snake Game Docker image
        run: |
          docker build . --tag snakegameregistry.azurecr.io/snakegame:latest
          docker push snakegameregistry.azurecr.io/snakegame:latest
