name: Make Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Snake Game Docker image
      run: docker build --pull --rm -f "DockerFile" -t snakegame:latest
